# Generated by Django 4.1.4 on 2023-03-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
